"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
$hostname\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_state\
$git_status\
$git_commit\
[](fg:color_aqua)\
$fill\
([](fg:color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$deno\
$php\
$java\
$kotlin\
$haskell\
$python\
$dart\
$cmake\
$pixi\
$docker_context\
$conda\
$package\
[](fg:color_blue))\
([](fg:color_bg3)\
$localip\
[](fg:color_bg3))\
[](fg:color_bg1)\
$status\
$jobs\
$cmd_duration\
$time\
[](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#1f2933'
color_bg1 = '#c8c0b2'
color_bg2 = '#a79e90'
color_bg3 = '#b2a391'
color_blue = '#aab596'
color_aqua = '#809560'
color_green = '#72895c'
color_orange = '#b7c2a3'
color_purple = '#7c9061'
color_red = '#6c6250'
color_error = '#c75b5b'
color_yellow = '#d2c08c'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Alpaquita = ""
AlmaLinux = ""
Windows = "󰍲"
Ubuntu = ""
SUSE = ""
Raspbian = ""
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = ""
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = ""
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
DragonFly = ""
Emscripten = ""
FreeBSD = ""
Garuda = "󰛓"
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Mabox = ""
Mariner = ""
MidnightBSD = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
Unknown = ""
Void = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
style = "bg:color_orange fg:color_fg0"
ssh_symbol = "󰣀"
trim_at = ""
format = '[$ssh_symbol $hostname ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
read_only = ""
format = "[  $path( $read_only) ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
home_symbol = "~"

[directory.substitutions]
"Important Documents" = "󰈙"
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch( -> $remote_branch) ](fg:color_fg0 bg:color_aqua)]($style)'

[git_state]
style = "bg:color_aqua"
rebase = "󰢟 Rebasing"
merge = " Merging"
revert = "󰌥 Reverting"
cherry_pick = " Cherry-Picking"
bisect = "󰢟 Bisecting"
am = "󰶌 Applying-Mailbox"
am_or_rebase = "󰶌 Mailbox/󰢟 Rebasing"
format = '[[ $state( $progress_current/$progress_total) ](bold fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind)](fg:color_fg0 bg:color_aqua)]($style)'
conflicted = "=${count} "
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
untracked = "?${count} "
stashed = "$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[git_commit]
tag_disabled = false
tag_symbol = " "
style = "bg:color_aqua"
format = '[[$symbol$tag](fg:color_fg0 bg:color_aqua)]($style)'
only_detached = false

[fill]
symbol = " "

[aws]
symbol = ""

[gcloud]
symbol = "🇬️"

[buf]
symbol = ""

[crystal]
symbol = ""

[elixir]
symbol = ""

[elm]
symbol = ""

[fennel]
symbol = ""

[guix_shell]
symbol = ""

[haxe]
symbol = ""

[julia]
symbol = ""

[lua]
symbol = ""

[meson]
symbol = "󰔷"

[nim]
symbol = "󰆥"

[nix_shell]
symbol = ""

[ocaml]
symbol = ""

[package]
symbol = "󰏗"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[perl]
symbol = ""

[rlang]
symbol = "󰟔"

[ruby]
symbol = ""

[scala]
symbol = ""

[swift]
symbol = ""

[zig]
symbol = ""

[gradle]
symbol = ""

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[bun]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[deno]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $name)( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[cpp]
disabled = false
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $name)( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[dart]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[cmake]
symbol = "△"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[pixi]
style = "bg:color_blue"
format = '[[ $symbol( $environment) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_blue)]($style)'

[conda]
style = "bg:color_blue"
symbol = ""
format = '[[ $symbol( $environment) ](fg:color_fg0 bg:color_blue)]($style)'

[memory_usage]
disabled = false
symbol = "󰍛"
threshold = 75
style = "bg:color_bg2"
format = '[[ $symbol ${ram_pct} ](fg:color_fg0 bg:color_bg2)]($style)'

[localip]
disabled = false
ssh_only = true
style = "bg:color_bg3"
format = '[[󱦂 $localipv4](fg:color_fg0 bg:color_bg3)]($style)'

[jobs]
disabled = false
symbol = ""
style = "bg:color_bg1"
number_threshold = 1
format = '[[ $symbol$number ](fg:color_fg0 bg:color_bg1)]($style)'

[cmd_duration]
disabled = false
style = "bg:color_bg1"
min_time = 5000
show_milliseconds = false
format = '[[  $duration ](fg:color_fg0 bg:color_bg1)]($style)'
show_notifications = false

[status]
disabled = false
symbol = "✘ "
style = "bg:color_bg1"
format = '[[ $symbol$status ](fg:color_error bg:color_bg1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_error)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
